---
id: 09-error-handling
title: Error Handling
sidebar_label: Error Handling
---

In the previous chapter you encountered an error while executing a `Mutation.postCommentOnLink` operation.
In this chapter you will learn the origin of this error and learn how to properly handle it.

### Recap of the encountered error

This the resolver implementation that caused the issue when using a `linkId` that has no counter-part within the database.

```ts
const resolvers = {
  // ... other resolver maps ...
  Mutation: {
    // ... other Mutation object type field resolver functions ...
    postCommentOnLink: async (
      parent: unknown,
      args: { linkId: string; body: string },
      context: GraphQLContext,
    ) => {
      const comment = await context.prisma.comment.create({
        data: {
          body: args.body,
          linkId: parseInt(args.linkId),
        },
      })

      return comment
    },
  },
}
```

<Instruction>

Execute the following GraphQL operation on GraphiQL:

```graphql
mutation postCommentOnLink {
  postCommentOnLink(linkId: "99999999999", body: "This is my second comment!") {
    id
    body
  }
}
```

</Instruction>

Again, this should yield in the following error response:

```json
{
  "errors": [
    {
      "message": "Unexpected error.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["postCommentOnLink"],
      "extensions": {
        "originalError": {
          "message": "\nInvalid `context.prisma.comment.create()` invocation in\nhackernews/src/schema.ts:69:52\n\n   66   args: { linkId: string; body: string },\n   67   context: GraphQLContext,\n   68 ) => {\nâ†’  69   const comment = await context.prisma.comment.create(\n  Foreign key constraint failed on the field: `foreign key`",
          "stack": "Error: \nInvalid `context.prisma.comment.create()` invocation in\nhackernews/src/schema.ts:69:52\n\n   66   args: { linkId: string; body: string },\n   67   context: GraphQLContext,\n   68 ) => {\nâ†’  69   const comment = await context.prisma.comment.create(\n  Foreign key constraint failed on the field: `foreign key`\n    at cb (hackernews/node_modules/@prisma/client/runtime/index.js:38703:17)\n    at PrismaClient._request (hackernews/node_modules/@prisma/client/runtime/index.js:40859:18)"
        }
      }
    }
  ],
  "data": null
}
```

As you can see the error includes an `extensions` `originalError` field.
It includes a full stack-trace of the original error for finding the cause easily.

## Yoga Error Masking

In a production environment, a stack-trace that leaks to the outside world is a potential security threat as that information could be misused by malicous actors.

The `extensions` `originalError` field is only present within on an error if the server has been started with the `NODE_ENV` environment variable being set to `development`.

As you might remember this is only the case when you are starting the server using `npm run dev`.

<Instruction>

Start the GraphQL server using the `npm run start` script.

```bash
npm run start
```

Then execute the same operation again.

```graphql
mutation postCommentOnLink {
  postCommentOnLink(linkId: "99999999999", body: "This is my second comment!") {
    id
    body
  }
}
```

</Instruction>

Now you can see that there is no `originalError` within the errors array first object.

```json
{
  "errors": [
    {
      "message": "Unexpected error.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["postCommentOnLink"]
    }
  ],
  "data": null
}
```

This is great, but now we never know why our request failed ðŸ¤”and the error message `Unexpected error.` is also not helpful to anyone not aware of the exact resolver function implementation.

## Exposing safe error messages

Let's change the implementation to expose the much more helpful message `Cannot post common on non-existing link with id 'X'.` instead of `Unexpected error.`.

For doing, so you will use the `GraphQLYogaError` class that is exported from the `@graphql-yoga/node` package.

<Instruction>

Add the following catch handler for mapping a foreign key error into a `GraphQLYogaError`.

```typescript
// ... other imports ...
import { GraphQLYogaError } from '@graphql-yoga/node'
// ... other imports ...

const resolvers = {
  // ... other resolver maps ...
  Mutation: {
    // ... other Mutation object type field resolver functions ...
    postCommentOnLink: async (
      parent: unknown,
      args: { linkId: string; body: string },
      context: GraphQLContext,
    ) => {
      const comment = await context.prisma.comment
        .create({
          data: {
            body: args.body,
            linkId: parseInt(args.linkId),
          },
        })
        .catch((err: unknown) => {
          if (
            err instanceof PrismaClientKnownRequestError &&
            err.code === 'P2003'
          ) {
            return Promise.reject(
              new GraphQLYogaError(
                `Cannot post common on non-existing link with id '${args.linkId}'.`,
              ),
            )
          }
          return Promise.reject(err)
        })

      return comment
    },
  },
}
```

</Instruction>

The error code `P2003` indicates a foreign key contraint error. [You can learn more about it in the prisma documentation](https://www.prisma.io/docs/reference/api-reference/error-reference#p2003).
You use that code for identifying this edge case of a missing link and then throw a `GraphQLYogaError` with an useful error message instead.

<Instruction>

Restart the server using `npm run dev` and again execute the mutation operation using GraphiQL.

```graphql
mutation postCommentOnLink {
  postCommentOnLink(linkId: "99999999999", body: "This is my second comment!") {
    id
    body
  }
}
```

</Instruction>

You will receive a response with the `Cannot post common on non-existing link with id '99999999999'.` message.

```json
{
  "errors": [
    {
      "message": "Cannot post common on non-existing link with id '99999999999'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["postCommentOnLink"]
    }
  ],
  "data": null
}
```

<Instruction>

As you might have noticed, GraphQLYoga will exclude `GraphQLYogaError` errors thrown within the resolvers from masking the error masking.

That means everytime you want to expose an error to the outside world you should throw an `GraphQLYogaError` error.

At the same time any other unexpected error will automatically be masked from the outside world, bringing you sensible and safe defaults for a GraphQL Yoga production deployment!
