---
id: error-masking
title: Error Masking
sidebar_label: Error Masking
---

Yoga uses [the Envelop `useMaskedErrors`](https://www.envelop.dev/plugins/use-masked-errors) for automatically masking unexpected errors and thus preventing sensitive information leaking to clients.

Such errors could be caused by failing to establish connection to remote services such as databases or HTTP APIs. Nobody needs to know that your database server is not reachable.

## Getting started

Let's setup a simple schema that calls a remote service that is unavailable.

```ts
import { createServer } from '@graphql-yoga/node'
import { fetch } from 'cross-undici-fetch'

// Provide your schema
const server = createServer({
  maskedErrors: false,
  schema: {
    typeDefs: /* GraphQL */ `
      type Query {
        greeting: String!
      }
    `,
    resolvers: {
      Query: {
        greeting: async () => {
          // This service does not exist
          const greeting = await fetch('http://localhost:9876/greeting').then(
            (res) => res.text(),
          )

          return greeting
        },
      },
    },
  },
})

// Start the server and explore http://localhost:4000/graphql
server.start()
```

Executing the following operation will now result within a leaking error message that exposes information about internal API calls.

**GraphQL Operation**

```graphql
query {
  greeting
}
```

**Execution Result with leaking error message**

```json
{
  "errors": [
    {
      "message": "request to http://localhost:9876/greeting failed, reason: connect ECONNREFUSED 127.0.0.1:9876",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["greeting"]
    }
  ],
  "data": null
}
```

By setting the `maskedErrors` configuration option to `true`, we can automatically mask this error.

```ts
import { createServer } from '@graphql-yoga/node'
import { fetch } from 'cross-undici-fetch'

// Provide your schema
const server = createServer({
  schema: {
    typeDefs: /* GraphQL */ `
      type Query {
        greeting: String!
      }
    `,
    resolvers: {
      Query: {
        greeting: async () => {
          // This service does not exist
          const greeting = await fetch('http://localhost:9876/greeting').then(
            (res) => res.text(),
          )

          return greeting
        },
      },
    },
  },
  // Mask unexpected errors
  // true is the default options. Yoga is safe by default!
  maskedErrors: true,
})

// Start the server and explore http://localhost:4000/graphql
server.start()
```

**Execution Result with masked error message**

```json
{
  "errors": [
    {
      "message": "Unexpected error.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["greetings"]
    }
  ],
  "data": null
}
```

You now sucessfully enabled masking of all kinds of unexpected errors within your GraphQL schema!

## Receive original error in development

When developing locally seeing the original error within your Chrome Dev Tools might be handy for debugging. You might be tempted to disable the masked errors via the `maskedErrors` config option, however, **we do not recommend that at all!** Having development and production behavior as close as possible is very important for not having any surprises in production.

Instead we recommend enabling the Yoga development mode. (Note: if you don't set `maskedErrors`, it's the default behaviour, and it's good!)

```ts
import { createServer } from '@graphql-yoga/node'
import { fetch } from 'cross-undici-fetch'

// Provide your schema
const server = createServer({
  schema: {
    typeDefs: /* GraphQL */ `
      type Query {
        greeting: String!
      }
    `,
    resolvers: {
      Query: {
        greeting: async () => {
          // This service does not exist
          const greeting = await fetch('http://localhost:9876/greeting').then(
            (res) => res.text(),
          )

          return greeting
        },
      },
    },
  },
  maskedErrors: {
    isDev: true, // We don't recommend this.
  },
  // // when maskedErrors is not set, the default behavior is:
  // maskedErrors: {
  //   isDev: process.env.NODE_ENV === "development"
  // },
  // // So, Close to production & with `originalError` only on development. üëç
})

server.start()
```

**GraphQL Operation**

```graphql
query {
  greeting
}
```

This will add a more detailed error with a proper stacktrace to the errors extensions.

**GraphQL Error Response with original error extensions**

```json
{
  "errors": [
    {
      "message": "Unexpected error.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["greeting"],
      "extensions": {
        "originalError": {
          "message": "request to http://localhost:9876/greeting failed, reason: connect ECONNREFUSED 127.0.0.1:9876",
          "stack": "FetchError: request to http://localhost:9876/greeting failed, reason: connect ECONNREFUSED 127.0.0.1:9876\n    at ClientRequest.<anonymous> (C:\\Users\\XXXX\\Projects\\graphql-yoga\\node_modules\\node-fetch\\lib\\index.js:1483:11)\n    at ClientRequest.emit (events.js:376:20)\n    at Socket.socketErrorListener (_http_client.js:475:9)\n    at Socket.emit (events.js:376:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
        }
      }
    }
  ],
  "data": null
}
```

On Node.js the original error is always included when `process.env.NODE_ENV` is set to `"development"`.

On unix and windows systems the environment variable can be set when starting the server.

```bash
# Unix (Linux/MacOS)
NODE_ENV=development node server.js
# Windows
set NODE_ENV=development
node server.js
```

## Exposing expected errors

Sometimes it is feasible to throw errors within your GraphQL resolvers whose message should be send to clients instead of being masked. This can be achieved by using and throwing a `GraphQLYogaError` instead of a "normal" [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error).

E.g. you want to throw an error if a resource cannot be found by an ID.

```ts
import { createServer, GraphQLYogaError } from '@graphql-yoga/node'

const users = [
  {
    id: '1',
    login: 'Laurin',
  },
  {
    id: '2',
    login: 'Saihaj',
  },
  {
    id: '3',
    login: 'Dotan',
  },
]

// Provide your schema
const server = createServer({
  schema: {
    typeDefs: /* GraphQL */ `
      type User {
        id: ID!
        login: String!
      }
      type Query {
        user(byId: ID!): User!
      }
    `,
    resolvers: {
      Query: {
        user: async (_, args) => {
          const user = users.find((user) => user.id === args.byId)
          if (!user) {
            throw new GraphQLYogaError(`User with id '${args.byId}' not found.`)
          }

          return user
        },
      },
    },
  },
  // Mask unexpected errors
  maskedErrors: true,
})

// Start the server and explore http://localhost:4000/graphql
server.start()
```

**Query for non existing user**

```graphql
query {
  user(byId: "6") {
    id
  }
}
```

**Execution result with error message**

```json
{
  "errors": [
    {
      "message": "User with id '6' not found.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["user"]
    }
  ],
  "data": null
}
```

## Error codes and other extensions

Sometimes it is useful to enrich errors with additional information e.g. an error code that can be interpreted by the client.

Error extensions can be passed as the second parameter to the `GraphQLYogaError` constructor.

```ts
import { createServer, GraphQLYogaError } from '@graphql-yoga/node'

const users = [
  {
    id: '1',
    login: 'Laurin',
  },
  {
    id: '2',
    login: 'Saihaj',
  },
  {
    id: '3',
    login: 'Dotan',
  },
]

// Provide your schema
const server = createServer({
  schema: {
    typeDefs: /* GraphQL */ `
      type User {
        id: ID!
        login: String!
      }
      type Query {
        user(byId: ID!): User!
      }
    `,
    resolvers: {
      Query: {
        user: async (_, args) => {
          const user = users.find((user) => user.id === args.byId)
          if (!user) {
            throw new GraphQLYogaError(
              `User with id '${args.byId}' not found.`,
              // error extensions
              {
                code: 'USER_NOT_FOUND',
              },
            )
          }

          return user
        },
      },
    },
  },
  // Mask unexpected errors
  maskedErrors: true,
})

// Start the server and explore http://localhost:4000/graphql
server.start()
```

**Query for non existing user**

```graphql
query {
  user(byId: "6") {
    id
  }
}
```

**Execution result with error message**

```json
{
  "errors": [
    {
      "message": "User with id '6' not found.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": ["user"],
      "extensions": {
        "code": "USER_NOT_FOUND"
      }
    }
  ],
  "data": null
}
```

The extensions are not only limited to a `code` property. Any JSON serializable value can be passed as extensions.

```ts
throw new GraphQLYogaError(
  `User with id '${args.byId}' not found.`,
  // error extensions
  {
    code: 'USER_NOT_FOUND',
    userId: args.byId,
    foo: {
      some: {
        complex: ['structure'],
      },
    },
  },
)
```
